server.port = 8080

services.stats-service.url = http://localhost:9090
spring.datasource.url=jdbc:postgresql://localhost:5434/ewm_db
spring.datasource.username=ewm_user
spring.datasource.password=ewm_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always