CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS  events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        annotation TEXT NOT NULL,
        category_id BIGINT NOT NULL REFERENCES categories(id),
        description TEXT NOT NULL,
        event_date TIMESTAMP NOT NULL,
        lat DOUBLE PRECISION NOT NULL,
        lon DOUBLE PRECISION NOT NULL,
        paid BOOLEAN NOT NULL DEFAULT FALSE,
        participant_limit INT NOT NULL DEFAULT 0,
        request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
        title VARCHAR(255) NOT NULL,
        initiator_id BIGINT NOT NULL REFERENCES users(id),
        created_on TIMESTAMP NOT NULL,
        published_on TIMESTAMP,
        state VARCHAR(20) NOT NULL,
        confirmed_requests INT NOT NULL DEFAULT 0,
        views INT NOT NULL DEFAULT 0
);